### PR TITLE
Add New Example To Readme.md

### PR DESCRIPTION
**Pull request by AdamZaczek**
Hey, I made an example using Launchpad to test it out. This might prove useful because it has different types of relationships.

### CODE REVIEW

**Comment by stubailo** [comment]
Hey, there is quite a bit of commented code in there, perhaps you didn't save the most recent version?

**Comment by AdamZaczek** [comment]
Hey, I saved it again, should be ok now.

**Comment by AdamZaczek** [comment]
@stubailo I saved it again, it should be ok now.

**Comment by stubailo** [comment]
This is great!

**Comment by stubailo** [comment]
Do you have a twitter account? I want to tweet about this and mention you!

**Comment by AdamZaczek** [comment]
I actually never really used one but I might as well do it now 💯 Here it is: https://twitter.com/ZaczekAdam. Thanks!

**Comment by AdamZaczek** [comment]
I haven't really used it but might as well start doing so now. Here it is:
https://twitter.com/ZaczekAdam. Glad you like it! We spoke at GraphQL
Europe by the way ;)

2017-05-24 11:35 GMT+02:00 Sashko Stubailo <notifications@github.com>:

**Pull request merged**
